language: cpp
compiler:
  - gcc
cache: apt
before_install:
  - sudo apt-get -yqq update
  - sudo apt-get -fyq install
install:
  - sudo apt-get -yq install build-essential chrpath libssl-dev libfontconfig1-dev
before_script:
  - chmod +x ./build.sh
script:
  - ./build.sh --confirm --silent
